'use strict';

module.exports = {
  environments: {
    azure: {
      default: 'https://management.azure.com/',
      activeDirectoryAuthority: 'https://login.microsoft.com',
      management: 'https://management.core.windows.net/',
      arm: 'https://management.azure.com/',
      rm: 'https://management.azure.com/',
      keyvault: 'https://vault.azure.net',
      vault: 'https://vault.azure.net',
      datalake: 'https://datalake.azure.net/',
      database: 'https://database.windows.net/',
      azuresql: 'https://database.windows.net/',
      eventhubs: 'https://eventhubs.azure.net',
      servicebus: 'https://servicebus.azure.net',
      storage: 'https://storage.azure.com/',
    },
    azureUSGovernment: {
      default: 'https://management.usgovcloudapi.net/',
      activeDirectoryAuthority: 'https://login.microsoftonline.us',
      management: 'https://management.core.usgovcloudapi.net/',
      arm: 'https://management.usgovcloudapi.net/',
      rm: 'https://management.usgovcloudapi.net/',
      keyvault: 'https://vault.usgovcloudapi.net',
      vault: 'https://vault.usgovcloudapi.net',
      database: 'https://database.usgovcloudapi.net/',
      azuresql: 'https://database.usgovcloudapi.net/',
      servicebus: 'https://servicebus.usgovcloudapi.net',
      storage: 'https://.core.usgovcloudapi.net/',
    },
    azureGermany: {
      default: 'https://management.microsoftazure.de/',
      activeDirectoryAuthority: 'https://login.microsoftonline.de',
      management: 'https://management.core.cloudapi.de/',
      arm: 'https://management.microsoftazure.de/',
      rm: 'https://management.microsoftazure.de/',
      keyvault: 'https://vault.microsoftazure.de',
      vault: 'https://vault.microsoftazure.de',
      database: 'https://database.cloudapi.de/',
      azuresql: 'https://database.cloudapi.de/',
      servicebus: 'https://servicebus.cloudapi.de',
      storage: 'https://core.cloudapi.de/',
    },
    azureChina: {
      default: 'https://management.chinacloudapi.cn/',
      activeDirectoryAuthority: 'https://login.partner.microsoftonline.cn',
      management: 'https://management.core.chinacloudapi.cn/',
      arm: 'https://management.chinacloudapi.cn/',
      rm: 'https://management.chinacloudapi.cn/',
      keyvault: 'https://vault.azure.cn',
      vault: 'https://vault.azure.cn',
      database: 'https://database.chinacloudapi.cn/',
      azuresql: 'https://database.chinacloudapi.cn/',
      servicebus: 'https://servicebus.chinacloudapi.cn',
      storage: 'https://core.chinacloudapi.cn/',
    }
  }
};
